### ISSUE TITLE
Build script fails for multi-gpu environments

### ISSUE THREAD

**Issue by IsaacTay** [luigifreda/rosdocker#1]
The `get_current_nvidia_driver_version` command returns multiple strings in a multi-gpu environment (eg. `470 470`) which breaks the docker build command

**Comment by luigifreda** [comment]
Hi, 
I updated `get_current_nvidia_driver_version` (heritage for old images). You should be fine now. Let me know.

**Comment by IsaacTay** [comment]
:+1: Works fine now
