### ISSUE TITLE
pyslam docker build error

### ISSUE THREAD

**Issue by tamaron1820** [luigifreda/rosdocker#2]
Hi
I had this issue when I run pyslam docker build.
668.3 ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.14.0 (from versions: 2.12.0)
668.3 ERROR: No matching distribution found for tensorflow-gpu==1.14.0

Dockerfile_pyslam:104

 102 |     # the following to inform we are inside docker at build time
 103 |     RUN sudo touch /.dockerenv
 104 | >>> RUN cd pyslam && ./install_all.sh
 105 |

ERROR: failed to solve: process "/bin/sh -c cd pyslam && ./install_all.sh" did not complete successfully: exit code: 1

How can I solve this issue ? 
The environment I use is macOS.
Thanks

**Comment by luigifreda** [comment]
Hi, 
 I tested again this morning from Ubuntu 20 and it works (see the pic below). I see you are on Mac. Probably, the tensorflow-**gpu** is a problem from its docker repositories. 

Did you try installing pyslam directly on Mac?
See this document:  https://github.com/luigifreda/pyslam/blob/mac/MAC.md
Unfortunately, I am not able to provide support on Mac anymore. 

![Screenshot from 2023-11-01 14-03-23](https://github.com/luigifreda/rosdocker/assets/10080262/e924d5d0-e316-414f-933c-a63c3eed9f62)

**Comment by HenryScratch** [comment]
9a3d531
468.5   Stored in directory: /home/henryscratch/.cache/pip/wheels/57/f5/41/32f5a1f2b1012be55d33a36be92cd310ec0fe44c3fdc042783
468.5   Building wheel for wrapt (setup.py): started
468.5   Building wheel for wrapt (setup.py): finished with status 'done'
468.5   Created wheel for wrapt: filename=wrapt-1.11.2-cp38-cp38-linux_aarch64.whl size=81465 sha256=0a0b21dcb8e0f40728b07df9a674b0f08c1b0d9204d010faecb89128867e3e2c
468.5   Stored in directory: /home/henryscratch/.cache/pip/wheels/52/25/16/7e228f52ee876e9c9c66dfd6eaf6fb2f73f18629a74dcf7045
468.5 Successfully built kiwisolver psutil wrapt
468.5 Failed to build h5py
------
Dockerfile_pyslam:114
--------------------
 112 |     RUN sudo touch /.dockerenv 
 113 |     ENV USER=${user}
 114 | >>> RUN cd pyslam && ./install_all_venv.sh 
 115 |     RUN /bin/bash -c "echo 'source pyslam/pyenv-activate.sh' >> ~/.bashrc"
--------------------
ERROR: failed to solve: process "/bin/sh -c cd pyslam && ./install_all_venv.sh" did not complete successfully: exit code: 1

**Comment by luigifreda** [comment]
Hey @HenryScratch, 
I've just tested building pyslam docker container from scratch under linux and it works 

![Screenshot from 2024-09-02 11-50-32](https://github.com/user-attachments/assets/12fddc24-144a-4a7e-af7a-5fc959de692c)

**Comment by luigifreda** [comment]
I checked the docker build procedure under macOS too and fixed a couple of issues there (changes were pushed). Nevertheless, there are some well-known difficulties in running OpenGL-based apps within docker under macOS.

The best procedure to install `pyslam` under macOS is to use the install script `install_all_venv.sh` directly in the host system (no docker). Check the main `pyslam` README for more details.
