### ISSUE TITLE
There is no useful ROS command in noetic_cuda

### ISSUE THREAD

**Issue by LoganCome** [luigifreda/rosdocker#3]
Dear author,
I have installed the noetic_cuda container, however, there is no useful ROS command in it, the output is as following:

[main_noetic_cuda]boyee@EdgeCloud:~/Work/plvs/Scripts (master)$ ros2
bash: ros2: command not found

I also have source /opt/ros/.....bash

The output is also as this.

**Comment by luigifreda** [comment]
Hi,
thanks for your feedback. Noetic is ROS 1, not ROS 2.
You can use the ros (1) command line
http://wiki.ros.org/ROS/CommandLineTools

Thererefore, `ros2` stuff is not installed.
